name: tf-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - tensorflow=2.13.0
  - tensorflow-estimator=2.13.0
  - tensorboard
  - pip:
      - keras==2.13.1
      - protobuf==3.20.3
      - requests
      - tensorboard-plugin-wit
      - tensorflow-io-gcs-filesystem
      - termcolor
      - threadpoolctl
      - typing-extensions
      - werkzeug
      - wheel
