name: tf-env
channels:
  - defaults
dependencies:
  - python=3.8.20
  - pip=24.2
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - tensorflow=2.13.0
  - tensorflow-estimator=2.13.0
  - tensorflow-intel=2.13.0
  - tensorboard=2.13.0
  - protobuf=3.20.3
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.5.2
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - keras==2.13.1
      - keras-preprocessing==1.1.2
      - markdown==3.7
      - packaging==24.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - typing-extensions==4.5.0
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - wheel==0.45.1
      - wrapt==1.17.2
      - zipp==3.20.2
